import { useEffect, useMemo, useRef, useState } from 'react'
import { CATEGORIES, type Category, type ImportantDate, type Recurrence } from './types'
import { countdownLabel, dateStatus, formatDate, loadData, nextOccurrence, parseISODate, saveData, STORAGE_KEY, todayISO, uid, validateBackup } from './utils'

type View = 'dashboard' | 'calendar' | 'settings'
type StatusFilter = 'all' | 'upcoming' | 'today' | 'overdue'
type Sort = 'nearest' | 'farthest' | 'recent'
type FormValues = Pick<ImportantDate, 'title' | 'category' | 'date' | 'notes' | 'reminderDays' | 'recurrence'>
const blankForm = (): FormValues => ({ title: '', category: 'Other', date: todayISO(), notes: '', reminderDays: 7, recurrence: 'none' })

export default function App() {
  const [dates, setDates] = useState<ImportantDate[]>(loadData)
  const [view, setView] = useState<View>('dashboard')
  const [formItem, setFormItem] = useState<ImportantDate | null | undefined>(undefined)
  const [selected, setSelected] = useState<ImportantDate | null>(null)
  const [query, setQuery] = useState(''); const [category, setCategory] = useState<'all' | Category>('all'); const [status, setStatus] = useState<StatusFilter>('all'); const [sort, setSort] = useState<Sort>('nearest')
  const [month, setMonth] = useState(() => new Date())
  useEffect(() => saveData(dates), [dates])
  const occurrences = useMemo(() => dates.map(nextOccurrence), [dates])
  const shown = useMemo(() => occurrences.filter(item => item.title.toLowerCase().includes(query.trim().toLowerCase()) && (category === 'all' || item.category === category) && (status === 'all' || dateStatus(item) === status)).sort((a, b) => sort === 'recent' ? b.createdAt.localeCompare(a.createdAt) : sort === 'nearest' ? a.date.localeCompare(b.date) : b.date.localeCompare(a.date)), [occurrences, query, category, status, sort])
  const counts = { upcoming: occurrences.filter(d => dateStatus(d) === 'upcoming').length, today: occurrences.filter(d => dateStatus(d) === 'today').length, overdue: occurrences.filter(d => dateStatus(d) === 'overdue').length }
  const saveItem = (values: FormValues) => { const now = new Date().toISOString(); const item: ImportantDate = formItem ? { ...formItem, ...values, title: values.title.trim(), updatedAt: now } : { ...values, title: values.title.trim(), id: uid(), createdAt: now, updatedAt: now }; setDates(all => formItem ? all.map(d => d.id === item.id ? item : d) : [item, ...all]); setFormItem(undefined); setSelected(null) }
  const remove = (id: string) => { if (window.confirm('Delete this important date?')) { setDates(all => all.filter(d => d.id !== id)); setSelected(null) } }
  const exportData = () => { const url = URL.createObjectURL(new Blob([JSON.stringify({ version: 1, dates }, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `life-date-planner-${todayISO()}.json`; link.click(); URL.revokeObjectURL(url) }
  const importData = (file: File) => { const reader = new FileReader(); reader.onload = () => { try { const imported = validateBackup(JSON.parse(String(reader.result))); if (!imported) throw Error(); setDates(imported); alert(`Imported ${imported.length} important date${imported.length === 1 ? '' : 's'}.`) } catch { alert('This is not a valid Life Date Planner backup.') } }; reader.readAsText(file) }
  return <div className="app"><header className="topbar"><button className="brand" onClick={() => setView('dashboard')} aria-label="Life Date Planner dashboard"><span className="brand-mark">LD</span><span><strong>Life Date Planner</strong><small>Never forget a date that matters.</small></span></button><nav className="top-actions" aria-label="Main navigation">{(['dashboard', 'calendar', 'settings'] as View[]).map(item => <button key={item} className={`nav ${view === item ? 'active' : ''}`} onClick={() => setView(item)}>{item[0].toUpperCase() + item.slice(1)}</button>)}<button className="primary" onClick={() => setFormItem(null)}>+ Add Important Date</button></nav></header>
    <main>{view === 'dashboard' && <Dashboard today={new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })} counts={counts} dates={shown} filtered={Boolean(query || category !== 'all' || status !== 'all')} query={query} category={category} status={status} sort={sort} setQuery={setQuery} setCategory={setCategory} setStatus={setStatus} setSort={setSort} add={() => setFormItem(null)} select={setSelected}/>} {view === 'calendar' && <Calendar month={month} setMonth={setMonth} dates={occurrences} select={setSelected}/>} {view === 'settings' && <Settings count={dates.length} exportData={exportData} importData={importData} clear={() => { if (window.confirm('Clear all saved dates? This cannot be undone unless you exported a backup.')) { localStorage.removeItem(STORAGE_KEY); setDates([]) } }}/>}</main>
    {formItem !== undefined && <DateForm item={formItem || undefined} save={saveItem} close={() => setFormItem(undefined)}/>} {selected && <Detail item={selected} close={() => setSelected(null)} edit={() => setFormItem(dates.find(d => d.id === selected.id) || null)} remove={() => remove(selected.id)}/>}</div>
}

function Dashboard(props: { today:string; counts:{upcoming:number;today:number;overdue:number}; dates:ImportantDate[]; filtered:boolean; query:string; category:'all'|Category; status:StatusFilter; sort:Sort; setQuery:(x:string)=>void; setCategory:(x:'all'|Category)=>void; setStatus:(x:StatusFilter)=>void; setSort:(x:Sort)=>void; add:()=>void; select:(d:ImportantDate)=>void }) { const { counts } = props; return <section className="container"><div className="hero"><div><p className="eyebrow">Today</p><h1>Plan the dates that matter.</h1><p className="today">{props.today}</p></div><div className="hero-summary"><strong>{counts.upcoming}</strong><span>upcoming important date{counts.upcoming === 1 ? '' : 's'}</span></div></div><div className="stats"><Stat value={counts.upcoming} label="Upcoming"/><Stat value={counts.today} label="Due today" tone="warning"/><Stat value={counts.overdue} label="Overdue" tone="danger"/></div><div className="section-head"><div><h2>What needs your attention?</h2><p>Important dates, arranged around what is closest.</p></div><button className="primary" onClick={props.add}>+ Add date</button></div><div className="toolbar"><input className="search" aria-label="Search dates by title" placeholder="Search dates..." value={props.query} onChange={e=>props.setQuery(e.target.value)}/><select aria-label="Filter by category" value={props.category} onChange={e=>props.setCategory(e.target.value as 'all'|Category)}><option value="all">All categories</option>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter by status" value={props.status} onChange={e=>props.setStatus(e.target.value as StatusFilter)}><option value="all">All statuses</option><option value="upcoming">Upcoming</option><option value="today">Due today</option><option value="overdue">Overdue</option></select><select aria-label="Sort dates" value={props.sort} onChange={e=>props.setSort(e.target.value as Sort)}><option value="nearest">Nearest date</option><option value="farthest">Farthest date</option><option value="recent">Recently added</option></select></div>{props.dates.length ? <div className="date-list">{props.dates.map(d=><DateCard key={d.id} item={d} click={()=>props.select(d)}/>)}</div> : <Empty filtered={props.filtered} add={props.add}/>}</section> }
function Stat({value,label,tone='' }:{value:number;label:string;tone?:string}) { return <div className={`stat ${tone}`}><strong>{value}</strong><span>{label}</span></div> }
function DateCard({item,click}:{item:ImportantDate;click:()=>void}) { return <button className={`date-card ${dateStatus(item)}`} onClick={click}><span className="date-icon">{item.title[0].toUpperCase()}</span><span className="date-main"><span className="card-top"><strong>{item.title}</strong><small className="badge">{item.category}</small></span><span className="date-text">{formatDate(item.date)} {item.recurrence !== 'none' && <small>↻ Repeats {item.recurrence}</small>}</span></span><strong className="countdown">{countdownLabel(item)}</strong><span className="chevron">›</span></button> }
function Empty({filtered,add}:{filtered:boolean;add:()=>void}) { return <div className="empty"><div className="empty-icon">✓</div><h3>{filtered ? 'No matching dates' : 'Never forget an important date again.'}</h3><p>{filtered ? 'Try changing your search or filters.' : 'Keep track of renewals, payments, deadlines, subscriptions, warranties, and other important dates in one simple place.'}</p>{!filtered && <button className="primary" onClick={add}>+ Add Important Date</button>}</div> }

function DateForm({item,save,close}:{item?:ImportantDate;save:(x:FormValues)=>void;close:()=>void}) { const [form,setForm]=useState<FormValues>(item ? {title:item.title,category:item.category,date:item.date,notes:item.notes||'',reminderDays:item.reminderDays,recurrence:item.recurrence} : blankForm()); return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()} role="presentation"><form className="modal" onSubmit={e=>{e.preventDefault(); if(form.title.trim()) save(form)}}><div className="modal-head"><div><p className="eyebrow">{item?'Edit important date':'New important date'}</p><h2>{item?'Update your date':'Add something to remember'}</h2></div><button type="button" className="icon-button" onClick={close} aria-label="Close">×</button></div><label>Title<input autoFocus required placeholder="e.g. Vehicle Insurance" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="two-col"><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value as Category})}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select></label><label>Date<input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label></div><label>Notes <span className="muted">(optional)</span><textarea rows={3} value={form.notes} placeholder="Anything useful to remember..." onChange={e=>setForm({...form,notes:e.target.value})}/></label><label>Reminder<select value={form.reminderDays ?? ''} onChange={e=>setForm({...form,reminderDays:e.target.value ? Number(e.target.value) : undefined})}><option value="">No reminder</option>{[1,3,7,15,30].map(d=><option key={d} value={d}>{d} day{d>1?'s':''} before</option>)}</select></label><fieldset><legend>Repeat</legend><div className="repeat-options">{(['none','monthly','yearly'] as Recurrence[]).map(x=><label key={x}><input type="radio" name="repeat" checked={form.recurrence===x} onChange={()=>setForm({...form,recurrence:x})}/>{x==='none'?'Does not repeat':x[0].toUpperCase()+x.slice(1)}</label>)}</div></fieldset><p className="privacy-note">Stored only in this browser. Nothing is sent to a server.</p><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">{item?'Save changes':'Save important date'}</button></div></form></div> }
function Detail({item,close,edit,remove}:{item:ImportantDate;close:()=>void;edit:()=>void;remove:()=>void}) { return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()} role="presentation"><article className="modal detail-modal"><div className="modal-head"><div><span className="badge">{item.category}</span><h2>{item.title}</h2></div><button className="icon-button" onClick={close} aria-label="Close">×</button></div><div className={`big-count ${dateStatus(item)}`}>{countdownLabel(item)}</div><div className="detail-grid"><div><span>Date</span><strong>{formatDate(item.date)}</strong></div><div><span>Repeat</span><strong>{item.recurrence === 'none' ? 'Does not repeat' : item.recurrence}</strong></div><div><span>Reminder</span><strong>{item.reminderDays ? `${item.reminderDays} days before` : 'None'}</strong></div></div>{item.notes && <div className="notes"><span>Notes</span><p>{item.notes}</p></div>}<div className="modal-actions"><button className="danger-button" onClick={remove}>Delete</button><button className="secondary" onClick={edit}>Edit</button><button className="primary" onClick={close}>Done</button></div></article></div> }

function Calendar({month,setMonth,dates,select}:{month:Date;setMonth:(d:Date)=>void;dates:ImportantDate[];select:(x:ImportantDate)=>void}) { const year=month.getFullYear(), mon=month.getMonth(), start=(new Date(year,mon,1).getDay()+6)%7, days=new Date(year,mon+1,0).getDate(), events=new Map<number,ImportantDate[]>(); dates.forEach(d=>{const x=parseISODate(d.date);if(x.getFullYear()===year&&x.getMonth()===mon)events.set(x.getDate(),[...(events.get(x.getDate())||[]),d])}); return <section className="container calendar-page"><div className="section-head"><div><p className="eyebrow">Calendar</p><h2>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><p>Select an important date to view it.</p></div><div className="month-nav"><button className="secondary" onClick={()=>setMonth(new Date(year,mon-1,1))} aria-label="Previous month">‹</button><button className="secondary" onClick={()=>setMonth(new Date(year,mon+1,1))} aria-label="Next month">›</button></div></div><div className="calendar"><div className="weekdays">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{Array.from({length:start+days},(_,i)=>i<start?null:i-start+1).map((day,i)=><div className={`calendar-cell ${day===new Date().getDate()&&mon===new Date().getMonth()&&year===new Date().getFullYear()?'current':''}`} key={i}>{day&&<><span className="day-number">{day}</span><div className="calendar-events">{(events.get(day)||[]).map(d=><button key={d.id} onClick={()=>select(d)}>{d.title}</button>)}</div></>}</div>)}</div></div></section> }
function Settings({count,exportData,importData,clear}:{count:number;exportData:()=>void;importData:(x:File)=>void;clear:()=>void}) { const ref=useRef<HTMLInputElement>(null); return <section className="container settings"><p className="eyebrow">Settings</p><h1>Your data, under your control.</h1><p className="settings-intro">Life Date Planner stores your {count === 1 ? 'date' : `${count} dates`} locally in this browser. Export a backup anytime.</p><div className="settings-card"><div><h2>Export data</h2><p>Download all your important dates as a JSON backup file.</p></div><button className="secondary" onClick={exportData}>Export Data</button></div><div className="settings-card"><div><h2>Import data</h2><p>Restore dates from a Life Date Planner backup file.</p></div><button className="secondary" onClick={()=>ref.current?.click()}>Import Data</button><input ref={ref} type="file" accept="application/json,.json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)importData(f);e.currentTarget.value=''}}/></div><div className="settings-card danger-setting"><div><h2>Clear all data</h2><p>Permanently delete every date saved in this browser.</p></div><button className="danger-button" onClick={clear}>Clear All Data</button></div><div className="privacy-box"><h2>Privacy</h2><p>Your dates live only in your browser’s local storage. This app has no accounts, no server, and no data collection.</p></div></section> }
